/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define HAVE_BACKTRACE 1

#define HAVE_CLOSE_RANGE 1

#define HAVE_FILE_SEALS 1

#define HAVE_IPA_PUBKEY 1

#define HAVE_LOCALE_T 1

#define HAVE_MEMFD_CREATE 1

#define HAVE_POSIX_IOCTL 1

#define IPA_CONFIG_DIR "/vendor/etc/libcamera/ipa:/usr/local/share/libcamera/ipa"

#define IPA_MODULE_DIR "/usr/local/lib/libcamera/ipa"

#define IPA_PROXY_DIR "/usr/local/libexec/libcamera"

#define LIBCAMERA_DATA_DIR "/usr/local/share/libcamera"

#define LIBCAMERA_SYSCONF_DIR "/vendor/etc/libcamera"

